Feature/jimon maker improvement
funapon/TechnoloVenus pull request #9
Opened 2019-09-24 15:38 UTC by funayu

・タイトルロゴ、ボタンのデザイン修正
・デフォルトのペン色を修正（青→グレー）
・背景色を設定できるよう修正
・リファクタリングの実施

2019-09-25 15:25 UTC, Yosuke-Nishizawa commented on src/main/resources/static/js/pattern_maker.js
> +const canvasDraw = document.getElementById("canvasDraw");
draw, grid, patternでクラス分けしてほしい

2019-09-25 15:25 UTC, Yosuke-Nishizawa commented on src/main/resources/static/js/pattern_maker.js
> +function setupCanvasDraw() {
setupよりinitのほうがわかりやすい

2019-09-25 15:25 UTC, Yosuke-Nishizawa commented on src/main/resources/static/js/pattern_maker.js
> +const gridColor = "#CCCCCC";
この値は不変なので定数としてGRID_COLORとしてほしい

2019-09-25 15:25 UTC, Yosuke-Nishizawa commented on src/main/resources/static/js/pattern_maker.js
> +    // 線の色を設定する
グリッド描画を別メソッドにしてもらえるとスッキリすると思う

2019-09-25 15:25 UTC, Yosuke-Nishizawa commented on src/main/resources/static/js/pattern_maker.js
> +  if(isMouseDown) {
こう書くより
```
if (isMouseDown === false) return;
...
```
と書いたほうがインデントが浅くなっていいよ

2019-09-25 15:25 UTC, Yosuke-Nishizawa commented on src/main/resources/static/js/pattern_maker.js
> +// イベントリスナーの追加
JSファイルがある程度長いので、イベント追加は別ファイルにしたほうがよさそう

2019-09-25 15:25 UTC, Yosuke-Nishizawa commented on src/main/resources/templates/pattern_maker.html
> +    <input type="radio" name="size" class="size" id="size_4" data-size="4" checked>4×4
4x4や下のペンの太さ:など値が裸なのでspanやlabelなどで囲ったほうがあとでCSSを当てたい場合にやりやすい

2019-09-30 14:16 UTC, funayu commented on src/main/resources/static/js/pattern_maker.js
> +// イベントリスナーの追加
initCanvasDrawがメインファイルの処理に存在するから、やり方はこんな感じになる？
https://qiita.com/ydzum1123/items/afcb31236502997dc19d

2019-09-30 14:23 UTC, funayu commented on src/main/resources/static/js/pattern_maker.js
> +function setupCanvasDraw() {
メソッド名を修正しました

2019-09-30 14:23 UTC, funayu commented on src/main/resources/static/js/pattern_maker.js
> +const gridColor = "#CCCCCC";
変数名を修正しました

2019-09-30 14:24 UTC, funayu commented on src/main/resources/static/js/pattern_maker.js
> +    // 線の色を設定する
グリッド描画処理をstrokeGridメソッドに切り出しました

2019-09-30 14:24 UTC, funayu commented on src/main/resources/static/js/pattern_maker.js
> +  if(isMouseDown) {
修正しました

2019-09-30 14:24 UTC, funayu commented on src/main/resources/templates/pattern_maker.html
> +    <input type="radio" name="size" class="size" id="size_4" data-size="4" checked>4×4
spanで囲むように修正しました

2019-10-06 13:55 UTC, Yosuke-Nishizawa commented on src/main/resources/static/js/pattern_maker.js
> +// イベントリスナーの追加
リンク先では関数を即時関数の中で定義しているからwindowオブジェクトの中に定義しているけど、今回の実装は関数をオープンに定義しているから↓みたいな感じなると思う。

ちなみに即時関数とは
```
(function() {
...
})();
```
みたいな感じに書くこと。

【定義例】
functions.js → 各種描画に必要な関数たち
```
function initCanvasDraw() {
...
}
function getCanvasDrawColor() {
...
}
...
```
event_difinitions.js → イベント定義
```
// イベントリスナーの追加
...
// クリアボタンが押された時
...
```
main.js → HTML読み込み時に処理されるファイル
```
initCanvasDraw();
showGrid();
```

2019-10-12 14:20 UTC, funayu commented on src/main/resources/static/js/pattern_maker.js
> +const canvasDraw = document.getElementById("canvasDraw");
修正しました

2019-10-12 15:56 UTC, funayu commented on src/main/resources/static/js/pattern_maker.js
> +// イベントリスナーの追加
修正しました

2019-10-14 07:55 UTC, Yosuke-Nishizawa commented on src/main/resources/static/js/pattern_maker.js
> +class Draw {
なんのためのクラスなのかをコメントで書いてほしい

2019-10-14 08:17 UTC, Yosuke-Nishizawa requested changes

2019-10-14 08:17 UTC, Yosuke-Nishizawa commented on src/main/resources/static/js/pattern_maker.js
> +// グリッドキャンバス上でマウスのボタンを押した時
◯◯した時っていうコメントのイベント定義はevent_definitions.jsに移せない？

2019-10-14 08:17 UTC, Yosuke-Nishizawa commented on src/main/resources/static/js/pattern_maker.js
> +// 描画するラインの始点
各役割ごとにJSファイルを分けたけど、pattern_maker.jsってなんの役割を担っているんだろう？
ファイル名を変えてクラス定義のファイルにしてもいい気がする。

2019-10-14 08:17 UTC, Yosuke-Nishizawa commented on src/main/resources/static/js/pattern_maker.js
> +// 描画するラインの始点
なんか、もしかしてこのファイルは不要？

2019-10-14 08:17 UTC, Yosuke-Nishizawa commented on src/main/resources/static/js/pattern_maker/event_definitions.js
> +// イベントリスナーの追加
このファイルではイベントの定義を行っているけど、これを一つのイベント定義関数として実装してはどうかと思う。
例えば、このファイルの内容を
`function defineEvents(draw)`として、main.jsでイベント定義として、この関数を呼べば、実装を見た人は「なるほどこのタイミングでイベントを定義しているのだな」ってわかると思う。

2019-10-14 08:17 UTC, Yosuke-Nishizawa commented on src/main/resources/static/js/pattern_maker/event_definitions.js
> +// イベントリスナーの追加
関数名も引数もあんまり考慮していないから必要に応じて変更してください。

2020-05-23 09:43 UTC, merged